# Generated by Django 3.0.3 on 2020-12-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irg_viz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='public',
        ),
    ]
